# Generated by Django 2.1.7 on 2019-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='picture',
            field=models.ImageField(blank=True, default='photos/imagenotuploaded.jpg', upload_to='photos/'),
        ),
    ]
